title: Welcome to my page
author: Manthan Keim
email: keimmanthan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple developer always willing to learn 
  new things.

# social links
twitter_username: your-twitter-handle
github_username:  @manthankeim

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
